### ISSUE TITLE
Redundant with `xorg-xcb-proto`

### ISSUE THREAD

**Issue by pkgw** [conda-forge/xcb-proto-feedstock#2]
Whoops. While working on providing the whole set of X.org client libraries with conda-forge, I didn't manage to discover that this package had already been created. The relatively new `xorg-xcb-proto` package is redundant with this one.

I'm biased but I'd recommend keeping `xorg-xcb-proto` and deprecating this one. That package is built on all three platforms, whereas this one is provided for Linux only. The other package also does a more thorough job of dealing with the versioning of the package's Python dependency. It also has a recipe and build scripts that are consistent with the rest of the X.org packages I've been working on.

I *think* this package is only used as a dependency of the Qt 5 package ... does anyone know if that's correct or not?

**Comment by ccordoba12** [comment]
That's correct. I don't have a problem with deprecating this package since you're in charge of it now.

@ocefpaf, @jakirkham, what do you say?

**Comment by ccordoba12** [comment]
Closing as per discussion in conda-forge/pthread-stubs-feedstock#3
